import argparse
import sys
import json
import os
from datetime import datetime
from typing import List

from phases.iron_gate import IronGate
from phases.identifier import Identifier
from phases.intelligence import Intelligence
from phases.tribunal import Tribunal

from tools.fmp import FMPClient
from tools.llm import LLMClient
from tools.search import SearchClient
from core.data_models import CompanyData, AnalysisReport


def analyze_ticker(ticker: str, fmp: FMPClient, llm: LLMClient, search: SearchClient,
                   force_deep_dive: bool = False) -> CompanyData:
    print(f"\n--- Analyzing {ticker} ---")
    data = CompanyData(ticker=ticker)

    # Phase 1: Iron Gate
    print(f"[{ticker}] Phase 1: Iron Gate...")
    ig = IronGate(fmp)
    data.iron_gate = ig.analyze(ticker)

    quote = fmp.get_quote(ticker)
    if quote:
        data.company_name = quote.get('name')
        data.current_price = quote.get('price')
        data.market_cap = quote.get('marketCap')

    if not data.iron_gate.passed:
        print(f"[{ticker}] Failed Iron Gate: {data.iron_gate.fail_reason}")
        if not force_deep_dive:
            return data
        print(f"[{ticker}] Proceeding despite Iron Gate failure (Force Mode).")

    # Phase 2: Identifier
    print(f"[{ticker}] Phase 2: Identifier...")
    ident = Identifier(llm)
    # We need a description. FMP profile has description.
    profile = fmp.get_profile(ticker)
    description = profile['description'] if profile else "Technology company"

    data.identifier = ident.identify(ticker, description)
    print(f"[{ticker}] Identified as {data.identifier.business_model} with KPIs: {data.identifier.specific_kpis}")

    # Phase 3: Intelligence
    print(f"[{ticker}] Phase 3: Saturated Intelligence...")
    intel = Intelligence(llm, search)
    data.intelligence = intel.gather(ticker, data.identifier)

    # Phase 4: Tribunal
    print(f"[{ticker}] Phase 4: The Tribunal...")
    tribunal = Tribunal(llm)
    data.tribunal = tribunal.judge(data)
    print(f"[{ticker}] Verdict: {data.tribunal.decision} ({data.tribunal.confidence})")

    return data


def save_report(data: CompanyData):
    if not data.tribunal:
        return

    timestamp = datetime.now().strftime("%Y-%m-%d")
    filename = f"REPORT_{data.ticker}_{timestamp}.md"

    # 安全获取可能为 None 的值
    price_str = f"${data.current_price:.2f}" if data.current_price else "N/A"
    market_cap_str = f"${data.market_cap / 1e9:.2f}B" if data.market_cap else "N/A"
    cagr_str = f"{data.iron_gate.revenue_cagr_5y:.1%}" if data.iron_gate.revenue_cagr_5y is not None else "N/A"
    q_growth_str = f"{data.iron_gate.revenue_growth_current_q:.1%}" if data.iron_gate.revenue_growth_current_q is not None else "N/A"
    peg_str = f"{data.iron_gate.peg_ratio:.2f}" if data.iron_gate.peg_ratio else "N/A"
    margin_slope_str = f"{data.iron_gate.gross_margin_slope:.4f}" if data.iron_gate.gross_margin_slope is not None else "N/A"
    opex_str = "Passed" if data.iron_gate.operating_leverage else (
        "Failed" if data.iron_gate.operating_leverage is False else "N/A")

    report_content = f"""# MGP V3.0 Analysis: {data.ticker}
**Date:** {timestamp}
**Verdict:** {data.tribunal.decision.value} ({data.tribunal.confidence.value} Confidence)
**Price:** {price_str} | **Market Cap:** {market_cap_str}

## Executive Summary
{data.tribunal.rationale}

---

## Phase 1: The Iron Gate (Quantitative)
* **Status**: {"Passed" if data.iron_gate.passed else "Failed"}
* **CAGR**: {cagr_str}
* **Current Q Growth**: {q_growth_str}
* **PEG Ratio**: {peg_str}
* **Gross Margin Slope**: {margin_slope_str}
* **OpEx Check**: {opex_str}

## Phase 2: DNA & KPIs
* **Business Model**: {data.identifier.business_model.value}
* **Key KPIs**: {', '.join(data.identifier.specific_kpis)}
* **Bear Case Hook**: {data.identifier.bear_case_hook}

## Phase 3: Saturated Intelligence
### KPI Performance
{json.dumps(data.intelligence.kpi_values, indent=2)}

### Soft Factors
* **Management**: {data.intelligence.management_integrity}
* **Moat**: {data.intelligence.product_moat}
* **Insider Activity**: {data.intelligence.insider_activity}
* **Dislocation Context**: {data.intelligence.dislocation_context}

## Phase 4: Tribunal Logic
* **Growth Thesis Intact**: {data.tribunal.growth_thesis_intact}
* **Valuation Fit**: {data.tribunal.valuation_fit}
* **True Discount**: {data.tribunal.is_true_discount}

---
*Generated by MGP V3.0 Auto-Analyst*
"""
    with open(filename, "w") as f:
        f.write(report_content)
    print(f"Report saved to {filename}")


def main():
    parser = argparse.ArgumentParser(description="Mahaney Growth Protocol V3.0")
    parser.add_argument("--tickers", type=str, default="DUOL", help="Comma-separated list of tickers")
    parser.add_argument("--force", action="store_true", help="Force deep dive even if Iron Gate fails")
    args = parser.parse_args()

    if not args.tickers:
        print("Please provide tickers using --tickers AAPL,MSFT")
        return

    tickers = [t.strip().upper() for t in args.tickers.split(",")]

    fmp = FMPClient()
    llm = LLMClient()
    search = SearchClient()

    results = []

    for ticker in tickers:
        try:
            data = analyze_ticker(ticker, fmp, llm, search, force_deep_dive=args.force)
            results.append(data.model_dump())
            if data.tribunal:
                save_report(data)
        except Exception as e:
            print(f"Error analyzing {ticker}: {e}")
            import traceback
            traceback.print_exc()

    with open("results.json", "w") as f:
        json.dump(results, f, indent=2)
    print("All analyses complete. Saved to results.json.")


if __name__ == "__main__":
    main()
