from core.data_models import CompanyData
from datetime import datetime

# ========== Bilingual Label Map ==========
_LABELS = {
    # Report Header
    "report_title":        {"en": "MGP V3.5 Blue Sky Report", "zh": "MGP V3.5 蓝天报告"},
    "date":                {"en": "Date", "zh": "日期"},
    "verdict":             {"en": "Verdict", "zh": "裁定"},
    "confidence":          {"en": "Confidence", "zh": "置信度"},
    "strategic_def":       {"en": "Strategic Definition", "zh": "战略定义"},
    "physics":             {"en": "Physics", "zh": "技术形态"},
    "price":               {"en": "Price", "zh": "价格"},
    "market_cap":          {"en": "Market Cap", "zh": "市值"},
    # Phase Titles
    "exec_summary":        {"en": "Executive Summary", "zh": "执行摘要"},
    "ph0":                 {"en": "Phase 0: The Gatekeeper", "zh": "Phase 0: 门槛熔断"},
    "ph1":                 {"en": "Phase 1: Deep Audit", "zh": "Phase 1: 深度审计"},
    "ph2":                 {"en": "Phase 2: Shadow Audit", "zh": "Phase 2: 影子验证"},
    "ph3":                 {"en": "Phase 3: Intelligence", "zh": "Phase 3: 软性情报"},
    "ph4":                 {"en": "Phase 4: Blue Sky", "zh": "Phase 4: 蓝天展望"},
    "ph5":                 {"en": "Phase 5: Catalysts & Waves", "zh": "Phase 5: 势能与催化"},
    "ph6":                 {"en": "Phase 6: Strategic Pricing", "zh": "Phase 6: 战略定价"},
    "ph7":                 {"en": "Phase 7: Physics VPA", "zh": "Phase 7: 量价物理学"},
    "ph8":                 {"en": "Phase 8: Final Tribunal", "zh": "Phase 8: 最终审判"},
    # Common
    "result":              {"en": "Result", "zh": "结果"},
    "fail_reason":         {"en": "Fail Reason", "zh": "失败原因"},
    "signal":              {"en": "Signal", "zh": "信号"},
    "passed":              {"en": "Passed", "zh": "通过"},
    "failed":              {"en": "Failed", "zh": "未通过"},
    "none":                {"en": "None", "zh": "无"},
    # Deep Audit (Phase 1)
    "detailed_metrics":    {"en": "Detailed Metrics", "zh": "详细指标"},
    "insider_breakdown":   {"en": "Insider Selling Breakdown (Institutional-Grade)", "zh": "内部人抛售分析（机构级）"},
    "insider_note":        {"en": "Insider Note", "zh": "内部人备注"},
    # Shadow Audit (Phase 2)
    "logic_evidence":      {"en": "Logic & Evidence", "zh": "逻辑与证据"},
    # Intelligence (Phase 3)
    "mgmt_integrity":      {"en": "Management Integrity", "zh": "管理层诚信"},
    "competitive_moat":    {"en": "Competitive Moat", "zh": "竞争护城河"},
    "insider_activity":    {"en": "Insider Activity", "zh": "内部人交易"},
    "dislocation_ctx":     {"en": "Dislocation Context", "zh": "价格错杀分析"},
    "kpi_table":           {"en": "Key Performance Indicators", "zh": "关键绩效指标"},
    # Blue Sky (Phase 4)
    "tam_logic":           {"en": "TAM Explosion Logic", "zh": "TAM 扩张逻辑"},
    "second_curve":        {"en": "Second Growth Curve (R&D Effectiveness)", "zh": "第二增长曲线（研发效能）"},
    "strong_second_curve": {"en": "Strong Second Curve Confirmed", "zh": "强第二曲线确认"},
    # Catalysts (Phase 5)
    "thematic_wave":       {"en": "Primary: Thematic Wave", "zh": "一级催化：全行业势能"},
    "hard_events":         {"en": "Secondary: Hard Events", "zh": "二级催化：硬事件"},
    "analysis":            {"en": "Analysis", "zh": "分析"},
    "supp_signals":        {"en": "Supplementary Signals", "zh": "补充信号"},
    "upcoming_events":     {"en": "Upcoming Events", "zh": "即将到来的事件"},
    "wave":                {"en": "Wave", "zh": "浪潮"},
    "strength":            {"en": "Strength", "zh": "强度"},
    "variant_perception":  {"en": "Variant Perception", "zh": "预期差"},
    "coattail_effect":     {"en": "Coattail Effect", "zh": "跟风效应"},
    # Strategy (Phase 6)
    "step1_val_scrub":     {"en": "Step 1: Valuation Scrub", "zh": "步骤 1：估值清洗"},
    "step2_fortress":      {"en": "Step 2: Fortress Test (Tier Level)", "zh": "步骤 2：堡垒测试（层级）"},
    "step3_bluesky":       {"en": "Step 3: Blue Sky Re-Rating", "zh": "步骤 3：蓝天重估"},
    "step4_matrix":        {"en": "Step 4: Executive Matrix", "zh": "步骤 4：决策矩阵"},
    # Physics (Phase 7)
    "tech_indicators":     {"en": "Technical Indicators", "zh": "技术指标"},
    "signal_analysis":     {"en": "Signal Analysis", "zh": "信号分析"},
    "ai_dynamics":         {"en": "🌌 AI Physical Dynamics Analysis", "zh": "🌌 AI 物理动力学分析"},
    "conclusion":          {"en": "Conclusion", "zh": "结论"},
    "recommendation":      {"en": "Recommendation", "zh": "建议"},
    # Tribunal (Phase 8)
    "core_judgments":       {"en": "Core Judgments", "zh": "核心判定"},
    "checklist":           {"en": "60-Second Checklist", "zh": "60 秒检查清单"},
    "macro_val":           {"en": "Macro-Adjusted Valuation", "zh": "宏观调整估值"},
    # Footer
    "references":          {"en": "References & Sources", "zh": "参考来源"},
    "appendix":            {"en": "Appendix: Core Terminology", "zh": "附录：核心术语"},
    "generated_by":        {"en": "Generated by MGP V3.5 Blue Sky Engine", "zh": "由 MGP V3.5 蓝天引擎生成"},
}

def _L(key: str, lang: str) -> str:
    """Get label in given language, fallback to English."""
    return _LABELS.get(key, {}).get(lang, _LABELS.get(key, {}).get("en", key))

def generate_report_content_v35(data: CompanyData, lang: str = "en") -> str:
    """Generate V3.5 Blue Sky Report - Bilingual (en/zh)"""
    decision = data.tribunal.decision.value if data.tribunal else "N/A"
    
    # Strategic Definition
    strategic_def = ""
    if data.strategic_pricing and data.strategic_pricing.strategic_definition:
        strategic_def = data.strategic_pricing.strategic_definition.value
    
    # Physics Icons
    physics_status = "Neutral"
    if data.physics:
        if data.physics.is_ignition:
            physics_status = "🚀 IGNITION"
        elif data.physics.is_accumulation:
            physics_status = "🔋 ACCUMULATION"
        elif data.physics.is_broken_trend:
            physics_status = "⚠️ BROKEN TREND"
    
    # Build Deep Audit Details
    deep_audit_details = ""
    if data.deep_audit:
        da = data.deep_audit

        # Insider Analysis Sub-Section
        insider_status = "No" 
        if da.insider_selling_risk:
            insider_status = "🚩 RED FLAG"
        elif da.insider_score >= 2:
            insider_status = "⚠️ WARNING"
        elif da.insider_score == 1:
            insider_status = "✓ Minor"
        
        insider_sub = ""
        if da.insider_details:
            d = da.insider_details
            insider_sub = f"""
#### {_L("insider_breakdown", lang)}
| Dimension | Value |
|-----------|-------|
| Total Sells (Form 4) | {d.get('total_sells', 'N/A')} |
| Operator (C-Level) Sells | {d.get('operator_sells', 'N/A')} |
| Investor (VC/PE/Director) Sells | {d.get('investor_sells', 'N/A')} |
| Max Disposition Intensity | {f"{d['max_intensity']:.1%}" if d.get('max_intensity') is not None else 'N/A'} |
| Worst Offender | {d.get('worst_person', 'N/A')} |
| 6M Price Return | {f"{d['price_return_6m']:.1%}" if d.get('price_return_6m') is not None else 'N/A'} |
| Selling into Weakness | {"🚩 YES" if d.get('selling_into_weakness') else "No"} |
| **LLM Verdict** | **{d.get('verdict', 'N/A')}** |
"""
        elif da.insider_selling_message:
            insider_sub = f"\n> **{_L('insider_note', lang)}:** {da.insider_selling_message}\n"
        
        deep_audit_details = f"""
### {_L("detailed_metrics", lang)}
| Metric | Value | Formula/Source |
|--------|-------|----------------|
| Revenue CAGR (N-Year) | {f"{da.revenue_cagr_ny:.1%}" if da.revenue_cagr_ny is not None else "N/A"} | (Latest Rev / Oldest Rev)^(1/N) - 1 |
| EPS CAGR (N-Year) | {f"{da.eps_cagr_ny:.1%}" if da.eps_cagr_ny is not None else "N/A"} | (Latest EPS / Oldest EPS)^(1/N) - 1 |
| Q/Q Revenue Growth | {f"{da.revenue_growth_current_q:.1%}" if da.revenue_growth_current_q is not None else "N/A"} | (Current Q Rev - YoY Q Rev) / YoY Q Rev |
| PEG Ratio (TTM) | {f"{da.peg_ratio:.2f}" if da.peg_ratio is not None else "N/A"} | FMP Ratios TTM |
| SBC / Revenue | {f"{da.sbc_revenue_ratio:.1%}" if da.sbc_revenue_ratio is not None else "N/A"} | TTM SBC / TTM Revenue |
| Net Dilution (YoY) | {f"{da.share_count_growth:.1%}" if da.share_count_growth is not None else "N/A"} | Diluted Shares YoY Change |
| Rule of 40 | {f"{da.rule_of_40:.1%}" if da.rule_of_40 is not None else "N/A"} | Rev Growth + FCF Margin |
| NDR | {f"{da.ndr:.0%}" if da.ndr is not None else "N/A"} | SaaS Net Dollar Retention |
| RPO Growth | {f"{da.rpo_growth:.0%}" if da.rpo_growth is not None else "N/A"} | SaaS RPO YoY |
| Inventory Health | {da.inventory_health or "N/A"} | Inv Days trend vs Gross Margin |
| Book-to-Bill | {f"{da.book_to_bill:.2f}x" if da.book_to_bill is not None else "N/A"} | Hardware demand signal |
| Take Rate Trend | {da.take_rate_trend or "N/A"} | Marketplace monetization |
| Insider Selling | {insider_status} (Score: {da.insider_score}/3) | FMP SEC Form 4 + 3-Layer Analysis |
| Red Flags Total | {da.red_flags} | ≥ 2 = FAIL |
{insider_sub}"""

    
    # Build Shadow Audit Details
    shadow_audit_details = ""
    if data.shadow_audit:
        sa = data.shadow_audit
        shadow_audit_details = f"""
### {_L("logic_evidence", lang)}
- **LinkedIn Hiring Audit:** {sa.linkedin_hiring_audit or "Not checked"}
- **Customer Quality:** {sa.customer_quality_audit or "Not checked"}
- **Marketing Efficiency:** {sa.marketing_efficiency or "Not checked"}
- **App Store Rank:** {sa.app_store_rank or "Not checked"}
- **Sandbagging:** {sa.sandbagging_details or "Not checked"}
"""
    
    # Build Intelligence Details
    intelligence_details = ""
    if data.intelligence:
        intel = data.intelligence
        
        # KPI Values sub-section
        kpi_md = ""
        if intel.kpi_values:
            kpi_lines = [f"| {k} | {v} |" for k, v in intel.kpi_values.items()]
            kpi_md = f"\n### {_L('kpi_table', lang)}\n| KPI | Value |\n|-----|-------|\n" + "\n".join(kpi_lines)
        
        intelligence_details = f"""
### {_L("mgmt_integrity", lang)}
{intel.management_integrity or "N/A"}

### {_L("competitive_moat", lang)}
{intel.product_moat or "N/A"}

### {_L("insider_activity", lang)}
{intel.insider_activity or "N/A"}

### {_L("dislocation_ctx", lang)}
{intel.dislocation_context or "N/A"}
{kpi_md}
"""
    
    # Build Blue Sky Details (Phase 4)
    blue_sky_details = ""
    if data.blue_sky_phase and data.blue_sky_phase.blue_sky:
        bs = data.blue_sky_phase.blue_sky
        blue_sky_details = f"""
### {_L("tam_logic", lang)}
{bs.tam_expansion or "N/A"}

### {_L("second_curve", lang)}
{bs.rnd_effectiveness or "N/A"}

- **{_L("strong_second_curve", lang)}:** {"✅ Yes" if bs.is_strong_second_curve else "No"}
"""

    # Build Catalysts & Waves Details (Phase 5)
    catalysts_details = ""
    if data.catalysts:
        cat = data.catalysts
        thematic_wave = cat.thematic_waves or "None identified"
        wave_strength = cat.wave_strength or "N/A"
        events = ", ".join(cat.upcoming_events) if cat.upcoming_events else "N/A"
        catalysts_details = f"""
### {_L("thematic_wave", lang)}
**{_L("wave", lang)}:** {thematic_wave}
**{_L("strength", lang)}:** {wave_strength}

### {_L("hard_events", lang)}
**{_L("upcoming_events", lang)}:** {events}

**{_L("analysis", lang)}:**
{cat.catalyst_analysis or "N/A"}

### {_L("supp_signals", lang)}
- **{_L("variant_perception", lang)}:** {cat.variant_perception or "N/A"}
- **{_L("coattail_effect", lang)}:** {cat.coattail_effect or "N/A"}
"""

    # Build Strategic Pricing Details (Phase 6)
    strategy_details = ""
    if data.strategic_pricing:
        sp = data.strategic_pricing
        strategy_details = f"""
### {_L("step1_val_scrub", lang)}
- **Adjusted PE:** {f"{sp.adjusted_pe:.1f}" if sp.adjusted_pe is not None else "N/A"}
- **Reason:** {sp.adjustment_reason or "No adjustment"}

### {_L("step2_fortress", lang)}
**Tier:** {sp.tier_level.value if sp.tier_level else "N/A"}
**Rationale:** {sp.tier_rationale or "N/A"}

### {_L("step3_bluesky", lang)}
**Triggered:** {"✅ Yes (PEG limit relaxed to 2.5)" if sp.blue_sky_triggered else "No"}
**PEG Limit:** {sp.peg_limit}

### {_L("step4_matrix", lang)}
| Dimension | Value |
|-----------|-------|
| Catalyst Strength | {sp.catalyst_strength or "N/A"} |
| Valuation Status | {sp.valuation_status or "N/A"} |
| **Strategic Definition** | **{sp.strategic_definition.value if sp.strategic_definition else "N/A"}** |
| Action | {sp.action_instruction or "N/A"} |
"""

    # Build Physics Details (Phase 7)
    physics_details = ""
    if data.physics:
        p = data.physics
        physics_details = f"""
### {_L("tech_indicators", lang)}
| Indicator | Value | Condition |
|-----------|-------|-----------|
| Current Price | ${(p.current_price if p.current_price else 0):.2f} | - |
| SMA 20 | ${(p.sma_20 if p.sma_20 else 0):.2f} | 生命线 (Life Line) |
| SMA 50 | ${(p.sma_50 if p.sma_50 else 0):.2f} | 中期趋势线 |
| SMA 200 | ${(p.sma_200 if p.sma_200 else 0):.2f} | 长期趋势线 |
| Relative Volume | {f"{p.relative_volume:.1f}x" if p.relative_volume else "N/A"} | Vol / Avg Vol 20 |
| Daily Range | {f"{p.daily_range*100:.1f}%" if p.daily_range else "N/A"} | (High - Low) / Close |
| Close Strength | {f"{p.close_strength:.1%}" if p.close_strength else "N/A"} | (Close - Low) / (High - Low) |
| Price vs SMA20 | {"Above ✅" if p.current_price and p.sma_20 and p.current_price > p.sma_20 else "Below ⚠️"} | Trend |
| Days Below SMA20 | {p.days_below_sma20} | 连续跌破天数 |
| Days Below SMA50 | {p.days_below_sma50} | 连续跌破天数 |

### {_L("signal_analysis", lang)}
| Form | Feature | Meaning | Status |
|------|---------|---------|--------|
| 📦 Accumulation | Range < 2% + RVol > 1.5 | Quiet Accumulation | {"✅ DETECTED" if p.is_accumulation else "NOT MET"} |
| 🚀 Ignition | Price > SMA20 + RVol > 2.0 + Strong Close | Momentum Ignition | {"✅ DETECTED" if p.is_ignition else "NOT MET"} |
| 📉 Broken Trend | Close < SMA50 for 3+ days | Trend Death | {"⚠️ YES" if p.is_broken_trend else "NO"} |
| ⚡ High Risk | High RVol on down days | Institutional Dumping | {"⚠️ YES" if p.is_high_risk else "NO"} |
"""
        
        if p.ai_analysis:
            physics_details += f"""
### {_L("ai_dynamics", lang)}
**{_L("conclusion", lang)}:** {p.ai_conclusion}
**{_L("recommendation", lang)}:** {p.ai_recommendation}

{p.ai_analysis}
"""
    
    # Build Macro Valuation
    macro_val = ""
    if data.blue_sky_phase and data.blue_sky_phase.macro_valuation_analysis:
        macro_val = data.blue_sky_phase.macro_valuation_analysis

    # Build Tribunal Checklist
    tribunal_checklist_md = ""
    if data.tribunal and data.tribunal.checklist_results:
        checklist = data.tribunal.checklist_results
        
        # Define display mapping
        display_map = {
            "risk_fuse": "Risk Fuse (VIX < 30)",
            "audit_passed": "Audit Passed (Deep Audit)",
            "blue_sky": "Blue Sky Confirmed (Second Curve/TAM)",
            "strategic_match": "Strategic Match (Tier 1/2 or Cheap)",
            "wave_resonance": "Wave Resonance (Thematic Wave)",
            "physical_ignition": "Physical Ignition (Price > SMA20 + RVol)"
        }
        
        checklist_lines = []
        for k, passed in checklist.items():
            icon = "✅" if passed else "❌"
            label = display_map.get(k, k.replace("_", " ").title())
            checklist_lines.append(f"- [{icon}] **{label}**")
            
        tribunal_checklist_md = "\n".join(checklist_lines)
    else:
        tribunal_checklist_md = "Checklist data not available."


    # Build References Section
    references_md = ""
    if data.references:
        ref_lines = []
        # Deduplicate by URL
        seen_urls = set()
        for ref in data.references:
            if ref.url not in seen_urls:
                seen_urls.add(ref.url)
                title = ref.title.replace('\n', ' ').strip()
                ref_lines.append(f"- [{ref.id}] [{title}]({ref.url})")
        references_md = "\n".join(ref_lines)
    else:
        references_md = "No external references cited."


    content = f"""# {_L("report_title", lang)}: {data.ticker}{f" — {data.company_name}" if data.company_name else ""}
**{_L("date", lang)}:** {datetime.now().strftime("%Y-%m-%d")}
**{_L("verdict", lang)}:** {decision} ({data.tribunal.confidence.value if data.tribunal else "N/A"} {_L("confidence", lang)})
**{_L("strategic_def", lang)}:** {strategic_def or "N/A"}
**{_L("physics", lang)}:** {physics_status}
**{_L("price", lang)}:** ${(data.current_price if data.current_price else 0):.2f} | **{_L("market_cap", lang)}:** {f"${data.market_cap/1e9:.1f}B" if data.market_cap else "N/A"}

---

## {_L("exec_summary", lang)}
{data.tribunal.rationale if data.tribunal else 'N/A'}

---

## {_L("ph0", lang)}
- **Macro Mode:** {data.gatekeeper.macro_mode.value if data.gatekeeper else 'N/A'}
- **US 10Y Yield:** {f"{data.gatekeeper.us10y_yield:.2f}%" if data.gatekeeper and data.gatekeeper.us10y_yield else 'N/A'}
- **VIX:** {f"{data.gatekeeper.vix_value:.1f}" if data.gatekeeper and data.gatekeeper.vix_value else 'N/A'}
- **Sector Check:** {'✅ ' + _L("passed", lang) if data.gatekeeper and data.gatekeeper.sector_check_passed else '❌ ' + _L("failed", lang)}
- **Future 20% Rule:** {'✅ ' + _L("passed", lang) if data.gatekeeper and data.gatekeeper.future_revenue_cagr_3y and data.gatekeeper.future_revenue_cagr_3y > 0.2 else '⚠️ Warning'}

---

## {_L("ph1", lang)}
- **{_L("result", lang)}:** {'✅ ' + _L("passed", lang) if data.deep_audit and data.deep_audit.passed else '❌ ' + _L("failed", lang)}
- **{_L("fail_reason", lang)}:** {data.deep_audit.fail_reason if data.deep_audit and data.deep_audit.fail_reason else _L("none", lang)}
{deep_audit_details}

---

## {_L("ph2", lang)}
- **King Makers:** {'✅ Yes' if data.shadow_audit and data.shadow_audit.has_king_maker_clients else 'No'}
- **Organic Growth:** {'✅ Confirmed' if data.shadow_audit and data.shadow_audit.organic_growth_confirmed else 'Unconfirmed'}
- **Fake Tech:** {'⚠️ YES' if data.shadow_audit and data.shadow_audit.is_fake_tech else 'No'}
{shadow_audit_details}

---

## {_L("ph3", lang)}
{intelligence_details}

---

## {_L("ph4", lang)}
{blue_sky_details}

---

## {_L("ph5", lang)}
{catalysts_details}

---

## {_L("ph6", lang)}
{strategy_details}

---

## {_L("ph7", lang)}
- **{_L("signal", lang)}:** {physics_status}
{physics_details}

---

## {_L("ph8", lang)}

### {_L("core_judgments", lang)}
| Dimension | Result |
|-----------|--------|
| Growth Thesis Intact | {"✅ Yes" if data.tribunal and data.tribunal.growth_thesis_intact else "❌ No"} |
| Valuation Fit | {"✅ Yes" if data.tribunal and data.tribunal.valuation_fit else "❌ No"} |
| True Discount | {"✅ Yes" if data.tribunal and data.tribunal.is_true_discount else "❌ No"} |

### {_L("checklist", lang)}
{tribunal_checklist_md}

### {_L("macro_val", lang)}
{macro_val or "N/A"}

---

## 🔗 {_L("references", lang)}
{references_md}

---

## 📚 {_L("appendix", lang)}

| Term | Definition |
|------|------------|
| **CAGR** | Compound Annual Growth Rate (年均复合增长率) |
| **NDR** | Net Dollar Retention (净收入留存率) |
| **RPO** | Remaining Performance Obligations (剩余履约义务 - 未来收入) |
| **PEG** | PE / Growth Rate (市盈率相对盈利增长比率) |
| **Sandbagging** | Management strategy of hiding real potential (扮猪吃虎) |
| **Ignition** | Volume-backed breakout (点火 - 伴随巨大成交量的突破) |
| **SMA20** | 20-Day Simple Moving Average (20日均线 - 生命线) |
| **RVol** | Relative Volume = Today's Vol / 20-Day Avg Vol |

---
*{_L("generated_by", lang)}*
"""
    return content

if __name__ == "__main__":
    print(datetime.now().strftime("%Y-%m-%d"))